apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: entertainment-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: entertainment.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movie-website-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: movie-server-service
                port:
                  number: 5000
