name: Build and Deploy to DigitalOcean K8s

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # vue-frontend-lint:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: movie-website
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "22.17.0"

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run Linting
  #       run: npm run lint

  # node-backend-lint:
  #   needs: vue-frontend-lint
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: server
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "22.17.0"

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run Linting
  #       run: npm run lint

  docker-images-digitalocean-registry:
    # needs: node-backend-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - name: Build Backend Image
      #   run: docker build -t ${{ secrets.REGISTRY_NAME }}/movie-server:$(echo $GITHUB_SHA | head -c7) ./server
      - name: Build Frontend Image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/movie-website:$(echo $GITHUB_SHA | head -c7) ./movie-website
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      # - name: Push backend image to DigitalOcean Container Registry
      #   run: docker push ${{ secrets.REGISTRY_NAME }}/movie-server:$(echo $GITHUB_SHA | head -c7)
      - name: Push frontend image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/movie-website:$(echo $GITHUB_SHA | head -c7)
