name: Build and Deploy to DigitalOcean K8s

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vue-frontend-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: movie-website
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

  node-backend-lint:
    needs: vue-frontend-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

  docker-images-digitalocean-registry:
    needs: node-backend-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build Backend Image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/entertainment:server-$(echo $GITHUB_SHA | head -c7) ./server
      - name: Build Frontend Image
        run: |
          docker build \
              --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
              --build-arg VITE_API_KEY=${{ secrets.VITE_API_KEY }} \
              -t ${{ secrets.REGISTRY_NAME }}/entertainment:movies-${GITHUB_SHA::7} ./movie-website
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Push backend image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/entertainment:server-$(echo $GITHUB_SHA | head -c7)
      - name: Push frontend image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/entertainment:movies-$(echo $GITHUB_SHA | head -c7)

  deploy-to-doks:
    needs: docker-images-digitalocean-registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Update k8s image placeholders
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | head -c7)

          sed -i "s|MOVIE_SERVER_IMAGE|${{ secrets.REGISTRY_NAME }}/entertainment:server-$SHORT_SHA|g" k8s/movie-server-deployment.yaml
          sed -i "s|MOVIE_WEBSITE_IMAGE|${{ secrets.REGISTRY_NAME }}/entertainment:movies-$SHORT_SHA|g" k8s/movie-website-deployment.yaml
      - name: Replace env placeholders
        run: |
          SAFE_DB_URL=$(printf '%s' "${{ secrets.DB_URL }}" | sed 's/&/\\&/g')
          sed -i "s|DB_URL_VALUE|$SAFE_DB_URL|g" k8s/movie-server-deployment.yaml
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}
      - name: Deploy to Digital Ocean Kubernetes
        run: kubectl apply -f k8s/
